### PR TITLE
Added prettier workflow on each pull request

### PR DESCRIPTION
**Pull request by JeelRajodiya**
## Description
added the prettier workflow 

## Related Issue
#4  

## Motivation and Context
This workflow currently formats all the files on each pull request, even the ones that are not edited in the request. After some pull requests when all the code is formatted, I'm planning to change this workflow so that only edited files will be formatted on pull requests.

I'm also planning to add a prettier config file

### CODE REVIEW

**Comment by mirchandani-mohnish** [comment]
Hey.... I've seen the same, can you try and implement it for only changed files.
The thing is, once we commit this.... although it does not make any difference to the code, any other pull requests and pushes will unnecessarily show too many changes due to prettier. 

Can you make an attempt... Just a thought

**Comment by JeelRajodiya** [comment]
> Hey.... I've seen the same, can you try and implement it for only changed files. The thing is, once we commit this.... although it does not make any difference to the code, any other pull requests and pushes will unnecessarily show too many changes due to prettier.
> 
> Can you make an attempt... Just a thought

Yeah Sure

**Comment by JeelRajodiya** [comment]
@mirchandani-mohnish please review my code, I've formatted all files and changed the workflow so that only modified files will be formatted using prettier. 
Thanks.

**Review by mirchandani-mohnish — APPROVED** [review]
I think this seems fine. We can try out the same and change in case it fails at some point

**Pull request merged**
