### PR TITLE
added the signup route and JWT 

### PR DESCRIPTION
**Pull request by BhagatHarsh**
## Description

The issue is about adding JSON web token (JWT) for authorization on the website. 
I have changed a lot of things to complete the task; after the changes, we can now successfully send the email and password(*encrypted using bcrypt*) to the database to store the user data and generate the web Token. After that, when the user signs in, the password is compared with the password stored in the DB, and if they match, we generate a new Token for the user and go to the next route. Otherwise, an error is sent back to the client.

## Motivation and Context

I will go through each file changes for better understanding.

#### Inside server/routes/
The sigin file was changed to verify that the post request of signing in is working.
The signup file was created as requested in the issue.

#### Inside server/config/
A new file generateKeyPairs was added to generate a Private Key which is used for the JWT.
and the subsequent files server/config/id_rsa_priv.pem and server/config/id_rsa_pub.pem are the result of running the generateKeyPairs.

#### Inside server/controllers/auth.controller.js
The major changes happened here as the user's request is processed in this file.
In the Signin function, we are extracting the user email and password, verifying that the email and passowrd are of the users and then generating a new Token for the browser to store.

In the Signup function, the email and password of the user are noted, then we encrypt the password using bcrypt and store in into the DB. Generate the payload and the token using the jwt library and pass this information in the form of { token, user } as was addressed in the issue. 

## Screenshots (if appropriate):
This is the Data being entered into a JSON format via post request to the signup page.

The data is stored in the DB.

The data is verified in when you sign in. 

If the data is tampered then Error is shown.

### CODE REVIEW

**Comment by mirchandani-mohnish** [comment]
Hey.. Thanks a lot: Will be merging the same soon.. until then you could work on another issue

**Review by kavania2002 — CHANGES_REQUESTED** [review]
I request you to create ```auth.routes.js``` file and insert both signin and signup.
Too much files would complicate things.

**Comment by BhagatHarsh** [comment]
I have done the requested changes please review.
And while doing so found a bug about during signup and fixed it.

**Review by kavania2002 — APPROVED** [review]
Now, it looks better.
Great work.
By the way, you were only assigned to do signup but you did signin also, I appreciate it but next time do keep in mind.

**Pull request merged**
