### PR TITLE
updated the user.model schema with the necessary fields

### PR DESCRIPTION
**Pull request by im3dabasia**
## Description
I have modified the user model table. I have added the email field, googleId to store the unique login id that will be generated upon signing in with google,
Added a Validator library which has a isEmail function which will be used in validating the if the email is genuine or not (from the back-end)

### CODE REVIEW

**Comment by mirchandani-mohnish** [comment]
Hey! Sorry for the delay, give us a day more

**Review by kavania2002 — CHANGES_REQUESTED** [review]
It looks good but I think there should be a ```name``` attribute also.

**Comment by im3dabasia** [comment]
their is a `userName` attribute in the schema. this probably should suffice the name part, do you want me to rename `userName` to `name`?

**Comment by mirchandani-mohnish** [comment]
I think he means a name attribute along with the userName... the two can be different -- 

When we implement oauth, would the same change to profile... I am not sure of the same, but currently, I think that's what he means

**Pull request closed without merging**
